name: map_mastering
description: M.A.P Mastering Audio Pro - offline mastering with FFmpeg
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^4.1.0
  just_audio: ^0.9.40
  file_picker: ^8.1.0
  path_provider: ^2.1.4
flutter:
  uses-material-design: true
